version: "3.9"

services:
  db:
    container_name: db-adshowcase
    image: mariadb:11.3
    platform: linux/arm64/v8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-yii2}
      MYSQL_USER: ${MYSQL_USER:-yii2}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootsecret}
    volumes:
      - db-adshowcase:/var/lib/mysql
      - ./docker/mariadb/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d:ro
    networks: [traefik_private]

  php:
    container_name: php-adshowcase
    build: ./docker/php
    platform: linux/arm64/v8
    working_dir: /var/www/html
    volumes:
      - ../../:/var/www/html
    depends_on:
      - db
    networks: [traefik_private]

  nginx:
    container_name: nginx-adshowcase
    image: nginx:1.25-alpine
    platform: linux/arm64/v8
    volumes:
      - ../../:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.rule=Host(`${LOCAL_HOST:-localhost.adshowcase.com}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-local.entrypoints=web
      - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80
    networks:
      - traefik_private
      - traefik_proxy

volumes:
  db-adshowcase:

networks:
  traefik_private:
  traefik_proxy:
    external: true